name: AquaPerms
version: ${pluginVersion}
description: A plugin better than LuckPerms
author: XTHESilent
website: https://aquasplashmc.ddns.net/aquaperms
main: com.xthesilent.aquaperms.bukkit.loader.BukkitLoaderPlugin
load: STARTUP

# Mark the plugin as 1.13 compatible to avoid CB having to perform quite as much unnecessary
# remapping when the plugin is loaded. Note that despite what this setting might otherwise imply,
# LP is still compatible with pre-1.13 releases.
api-version: 1.13

# Load AquaPerms before Vault. This means that all plugins that (soft-)depend
# on Vault depend on AquaPerms too.
#
# This fixes issues caused by plugins obtaining the Vault service provider instance
# only once when they initially enable. (if they haven't depended on LP, our registration
# won't be there yet)
loadbefore: [Vault]

# Soft depend on LilyPad for messaging service impl
# Soft depend on ViaVersion for adventure protocol facet
softdepend: [LilyPad-Connect, ViaVersion]

commands:
  aquaperms:
    description: Manage permissions
    aliases: [ap, perm, perms, permission, permissions]
