name: AquaPerms
version: ${pluginVersion}
api: ["1.0.5"]
description: A plugin better than LuckPerms
author: XTHESilent
website: https://aquasplashmc.ddns.net/aquaperms

main: com.xthesilent.aquaperms.nukkit.loader.NukkitLoaderPlugin
load: STARTUP

commands:
  aquaperms:
    description: Manage permissions
    aliases: [ap, perm, perms, permission, permissions]
