modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/AquaPerms/AquaPerms/issues"

[[mods]]
    modId="aquaperms"
    version="${version}"
    displayName="AquaPerms"
    displayURL="https://aquasplashmc.ddns.net/aquaperms/"
    logoFile="aquaperms.png"
    credits="Luck"
    authors="Luck"
    description="A permissions plugin for Minecraft servers."